### ISSUE TITLE
README has Google link

### ISSUE THREAD

**Issue by ThatOneCalculator** [noriah/catnip#10]
I almost clicked on that link before seeing the tooltip. Please switch it from Google to something like a SearX mirror or at least DuckDuckGo/Qwant/Startpage

**Comment by ThatOneCalculator** [comment]
![image](https://user-images.githubusercontent.com/44733677/117922510-7197fa00-b2a7-11eb-87f7-c49c2147c607.png)
****

**Comment by ThatOneCalculator** [comment]
Bruh

**Comment by noriah** [comment]
the link is there by design

**Comment by ThatOneCalculator** [comment]
Can you like change it to SearX or something that doesn't track you?

**Comment by noriah** [comment]
no.
the link points to google because I actively chose for it to go to google.
the google results page is what I'm linking to. if the point was to inform the user, I would have linked wikipedia or some other source.
