### ISSUE TITLE
[input/ffmpeg] Windows DirectShow issues

### ISSUE THREAD

**Issue by HyperLemons** [noriah/catnip#17]
![adfsdfg](https://user-images.githubusercontent.com/36387099/229311341-97df4bb2-9aec-4d02-809b-7befc9adf501.PNG)

input\ffmpeg\dshow.go:31:9: not enough return values

        have (*execread.Session)

        want (*execread.Session, error)

**Comment by noriah** [comment]
Sorry about that. I don't have a windows system to test on, so sometimes things slip.

**Comment by HyperLemons** [comment]
Thanks, that fixed it. It installed (seemingly) correctly, but after trying multiple times I'm not able to get any devices listed with ffmpeg-dshow? I even went into my FlexASIO GUI to set the backend to DirectShow, which I usually keep on WASAPI, and still nothing.

![image](https://user-images.githubusercontent.com/36387099/229685978-ad44e817-5e63-402b-a184-b0e4a09c4552.png)

        $ catnip -b ffmpeg-dshow list-devices
        
        failed to get devices:  no devices found; ffmpeg output:


I also tried to reinstall with PortAudio to see if anything would change, but that didn't work either.

![image](https://user-images.githubusercontent.com/36387099/229685482-75dccd58-7256-4f9f-bb8f-d3a01207dc32.png)

        $ go install ./cmd/catnip -tags withportaudio
        malformed import path "-tags": leading dash
        package withportaudio is not in GOROOT (C:\Program Files\Go\src\withportaudio)

**Comment by noriah** [comment]
#### DirectShow
Can you run `ffmpeg -loglevel debug -f dshow -list_devices true -i` and paste the output here?

#### PortAudio

Go tags need to come before the package.
`go install -tags withportaudio ./cmd/catnip` should work.

**Comment by HyperLemons** [comment]
Something must have been wrong with my ffmpeg build, was giving me some issues so I reinstalled with the latest stable build (6.0 full). Here's the output of

        ffmpeg -loglevel debug -f dshow -list_devices true -i

![image](https://user-images.githubusercontent.com/36387099/229931424-b6c6cc0b-9482-46f9-9a21-41c31d184c93.png)

        libavutil      58.  2.100 / 58.  2.100
        libavcodec     60.  3.100 / 60.  3.100
        libavformat    60.  3.100 / 60.  3.100
        libavdevice    60.  1.100 / 60.  1.100
        libavfilter     9.  3.100 /  9.  3.100
        libswscale      7.  1.100 /  7.  1.100
        libswresample   4. 10.100 /  4. 10.100
        libpostproc    57.  1.100 / 57.  1.100
        Splitting the commandline.
        Reading option '-loglevel' ... matched as option 'loglevel' (set logging level) with argument 'debug'.
        Reading option '-f' ... matched as option 'f' (force format) with argument 'dshow'.
        Reading option '-list_devices' ... matched as AVOption 'list_devices' with argument 'true'.
        Reading option '-i' ...Missing argument for option 'i'.
        Error splitting the argument list: Invalid argument

Devices will list now, but it's only showing my microphones...

![image](https://user-images.githubusercontent.com/36387099/229932156-85597772-15c1-48d8-8da8-2f717a9771f1.png)

        all devices for "ffmpeg-dshow" backend. '*' marks default
        - Microphone (Yeti Stereo Microphone)
        - virtual-audio-capturer
        - Microphone Array (Realtek High Definition Audio)

**Comment by noriah** [comment]
Sadly that is a limitation of Ffmpeg and Windows DirectShow. As far as I know, you can only listen to audio sources (microphones, line-in).

I remember Windows had a way to make an audio source from an output device. Something like a monitor or mixer.

With other systems, you can connect to different audio streams.
