### ISSUE TITLE
What is the spectrum visualizer program you're running in the second demo vid?

### ISSUE THREAD

**Issue by GideonWolfe** [noriah/catnip#23]
it looks really cool

**Comment by noriah** [comment]
inside [CatnipJulia](https://github.com/noriah/catnip/tree/main/CatnipJulia) are some [julia](https://julialang.org/) components that can run [the script](https://github.com/noriah/catnip/blob/main/CatnipJulia/src/run_catnip.jl) which runs the graphical visualizer

you will likely need to edit the command inside the script that calls the catnip binary.

eventually I will have this put together better so its easier to run. the goal was to make a self contained script that could run it, but that hasn't worked out so far.

it currently requires manually installing some [julia packages](https://docs.julialang.org/en/v1/stdlib/Pkg/).

- Colors
- DataStructures
- GLMakie

then you can run `julia ./CatnipJulia/src/run_catnip.jl`

**Comment by GideonWolfe** [comment]
Thanks for the instructions, I'll give that a shot :)
